projects:
  CABoilerplate:
    schemaPath: amplify/backend/api/caboilerplate/build/schema.graphql
    includes:
      - src/shared/service/infrastructure/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/shared/service/infrastructure/API.ts
        docsFilePath: src/shared/service/infrastructure/graphql
        region: ap-northeast-1
        apiId: null
        maxDepth: 2
